//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppOwin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usuario()
        {
            this.consumo = new HashSet<consumo>();
        }
    
        public int id { get; set; }
        public string nome { get; set; }
        public string cpf_cnpj { get; set; }
        public string senha { get; set; }
        public string email { get; set; }
        public string endereco { get; set; }
        public string telefone { get; set; }
        public Nullable<System.DateTime> data_nascimento { get; set; }
        public string tipo { get; set; }
        public string sexo { get; set; }
        public Nullable<int> tempo_permanencia { get; set; }
        public Nullable<int> quantidade_pessoas { get; set; }
        public Nullable<double> meta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<consumo> consumo { get; set; }
    }
}
